#cloud-config
users:
  - name: harold
    gecos: Harold Gutierrez
    lock_passwd: false
    expiredate: '2090-09-01'
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/zsh
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMBMbWh7iWMy1rHzdwTIfjGDGJqn14kyRgZzLjh98bPgRGxJhHm/xLyDp+0FRvaEpUMFBtA7AN98ptBU8FSTxQq05ksbvKhdTNm9yt/MgyxQkPdttDDvkhWzlhTggAn+7u7JMhmzmL2CKstViDtpnP/BHvZ5V0grsskXTQhhsHvCu5Oecqxi/OKcBDD8ckaD37YVZc+hb35M2kMLkvXXJz/TdxUa/nM27N/GXTEaRPDNaEUbhrs6d3qKbSXSuKqSuS0U4E3lz34Dv/5NIalRuphetsM/VuWaKf5W+KKYYDXT4RHpZuRZok/To1uLxsmvHrCj50VX+AV/ncgsHoq99/ harold.calderon@Harolds-MacBook-Pro.local

  - name: ansible
    gecos: Ansible user
    lock_passwd: false
    expiredate: '2090-09-01'
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMBMbWh7iWMy1rHzdwTIfjGDGJqn14kyRgZzLjh98bPgRGxJhHm/xLyDp+0FRvaEpUMFBtA7AN98ptBU8FSTxQq05ksbvKhdTNm9yt/MgyxQkPdttDDvkhWzlhTggAn+7u7JMhmzmL2CKstViDtpnP/BHvZ5V0grsskXTQhhsHvCu5Oecqxi/OKcBDD8ckaD37YVZc+hb35M2kMLkvXXJz/TdxUa/nM27N/GXTEaRPDNaEUbhrs6d3qKbSXSuKqSuS0U4E3lz34Dv/5NIalRuphetsM/VuWaKf5W+KKYYDXT4RHpZuRZok/To1uLxsmvHrCj50VX+AV/ncgsHoq99/ harold.calderon@Harolds-MacBook-Pro.local

ssh_pwauth: True

# Set timezone
timezone: UTC

# Install packages
packages:
  - curl
  - zsh
  - git

# Remove cloud-init and download ZSH packages.
runcmd:
  - yum -y remove cloud-init
  - su - harold -c 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  - su - harold -c 'git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k'
  - su - harold -c 'sed -i.bak 's:robbyrussell:powerlevel10k/powerlevel10k:g' ~/.zshrc'
  - su - harold -c 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions'
  - su - harold -c 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting'
  - su - harold -c "sed -i.bak 's:plugins=(git):plugins=(git zsh-autosuggestions zsh-syntax-highlighting):g' ~/.zshrc"

# Configure where output will go
output:
  all: ">> /var/log/cloud-init.log"