---
- name: Test VM FIO
  hosts: all
  tasks:
  - name: Install required packages
    yum: 
      name:
        - fio
      state: present
  - name: Copy zsh configuration
    copy:
      src: '{{item}}'
      dest: /home/harold/
      owner: harold
      group: harold
    loop:
      - ./files/.zshrc
      - ./files/.p10k.zsh
