---
- name: Test VM FIO
  hosts: all
  tasks:
  - name: Install FIO package
    ansible.builtin.yum:
      name:
        - fio
      state: present
  - name: FIO Test
    ansible.builtin.command: "fio --name=fiotest --filename=/mnt/testfile --size=1Gb --rw=randrw --bs=8K --direct=1 --rwmixread=50 --numjobs=8 --ioengine=libaio --iodepth=32 --group_reporting --runtime=60 --startdelay=0"
    register: my_output
    changed_when: my_output.rc != 0
